export const LOAD_STANDING_DATA = "LOAD_STANDING_DATA";
export const LOAD_TEAM_DATA = "LOAD_TEAM_DATA";
export const POST_LIST_TEAM = "POST_LIST_TEAM"
export const POST_LIST_TEAM_EXCEPT = "POST_LIST_TEAM_EXCEPT"
export const LOAD_MATCH_DATA = "LOAD_MATCH_DATA"
export const UPDATE_MATCH_RESULT = "UPDATE_MATCH_RESULT"

export const UPDATE_DISPLAY = "UPDATE_DISPLAY"
